In [3]:
# 四则运算
def arithmetic_operations(a,b):
    add=a+b
    sub=a-b
    mul=a*b
    div=a/b
    return add,sub,mul,div

a=10
b=12
result=arithmetic_operations(a,b)
print(result[0],result[1],result[2],result[3])


22 -2 120 0.8333333333333334


In [6]:
# 矩阵乘法
def matrix_mul(A,B):
    #检查矩阵形状是否满足可乘条件 前一个矩阵的列数等于后一个矩阵的行数
    #A的列数 len(A[0]) 第一行的元素个数     B的行数 len(B)
    if len(A[0])!=len(B):
        raise ValueError("Error: check matrix size")
    else:
        C=[[0]*len(B[0])  for i in range(len(A))]
        
        #C的i行j列元素是 A的i行与B的j列做内积
        for i in range(len(A)):
            
            for j in range(len(B[0])):
                
                #内积
                for k in range(len(B[0])):
                    C[i][j]+=A[i][k]*B[k][j]
    return C
A=[[1,2,4],[2,3,1],[2,3,4]]
B=[[-1,2,3],[2,1,2],[2,1,1]]

print(matrix_mul(A,B))
        

[[11, 8, 11], [6, 8, 13], [12, 11, 16]]


In [7]:
# assert 插入断言
def divide(a,b):
    assert b!=0
    return a/b
result=divide(10,0)
print(result)

AssertionError: 

In [10]:
# 计算两个向量的内积
def inner_prod(a,b):
    """
    
    :param a: 一个向量 
    :param b: 另一个向量
    :return: 返回两个向量的内积
    """
    #检查两个向量的长度是否一致
    if len(a)!=len(b):
        raise ValueError("向量长度不同")
    
    result=0
    for i in range(len(a)):
        result+=a[i]*b[i]
    
    return result

a=[1.2,4,2]
b=[1,1,2]
print(f"the value is {inner_prod(a,b)}")

the value is 9.2


In [18]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,0])

dot_prod=np.dot(a,b)
print(dot_prod)

A=np.array([[1,2,10,20],[3,4,30,40]])
B=np.array([[1,3],[10,30],[2,3],[20,40]])

C=A@B;print(C)
D=B@A;print(D)


80
[[ 441  893]
 [ 903 1819]]
[[  10   14  100  140]
 [ 100  140 1000 1400]
 [  11   16  110  160]
 [ 140  200 1400 2000]]


In [20]:
# 比较自带运算方法与手动运算方法的时间差异
from numpy.random import randint

num=200
A=randint(0,10,size=(num,num))
B=randint(0,10,(num,num))

import  time
start_time=time.time()
C=A@B
end_time=time.time()
time_used=end_time-start_time

print("--- %s seconds ---" %time_used)
print(C)

C = np.zeros((num,num))
# num * num大小全0方阵
# 手动计算矩阵乘法
start_time = time.time() # 开始时刻
for i in range(len(A)):
 for j in range(len(B[0])):
  for k in range(len(B)):
    C[i][j] += A[i][k] * B[k][j]
stop_time=time.time()
time_used = stop_time - start_time
print("--- %s seconds ---" %time_used)


--- 0.004004716873168945 seconds ---
[[3867 3913 4081 ... 4065 4404 4340]
 [4050 4385 4166 ... 4364 4654 4653]
 [3764 3814 3725 ... 3999 4228 4021]
 ...
 [3820 3973 3994 ... 3985 4304 4233]
 [4023 4035 4072 ... 4192 4386 4452]
 [4107 4174 4205 ... 4268 4575 4397]]
--- 5.51157546043396 seconds ---


In [22]:
#矩阵转置
def transpose(matrix):
    transposed=[]
    rows=len(matrix)
    cols=len(matrix[0])
    
    for j in range(cols):
        transposed_row=[matrix[i][j] for i in range(rows)]
        transposed.append(transposed_row)
        
    return transposed

A=[[1,2,3],[2,3,4],[4,2,1]]
B=transpose(A)
print(B)

[[1, 2, 4], [2, 3, 2], [3, 4, 1]]


In [27]:
# 阶乘
def f(n):
    if n==0 or n==1:
        return 1
    else:
        return f(n-1)*n
    
print(f(1))

1


In [30]:
import numpy as np
??np.sin

In [31]:
from numpy import pi
class Circle:
    #构造函数
    def __init__(self,radius):
        self.radius=radius
    
    # 求面积
    def area(self):
        return pi*self.radius*self.radius
    
    def length(self):
        return 2*pi*self.radius

cir_1=Circle(12)
print(cir_1.area())
print(cir_1.length())

452.3893421169302
75.39822368615503
